<?php

namespace Laf\UI\Grid\PhpGrid;

use Box\Spout\Common\Entity\Style\Border;
use Box\Spout\Common\Entity\Style\Color;
use Box\Spout\Common\Exception\IOException;
use Box\Spout\Writer\Common\Creator\Style\BorderBuilder;
use Box\Spout\Writer\Common\Creator\Style\StyleBuilder;
use Box\Spout\Writer\Exception\WriterNotOpenedException;
use JetBrains\PhpStorm\NoReturn;
use JetBrains\PhpStorm\Pure;
use Laf\Database\BaseObject;
use Laf\Database\Db;
use Laf\Util\Util;
use Laf\UI\Grid\PhpGrid\Column;
use Box\Spout\Writer\Common\Creator\WriterEntityFactory;
use PhpOffice\PhpSpreadsheet\Shared\Font;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Exception;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;


/**
 * Class PhpGrid
 * @package Laf\UI\Grid\PhpGrid
 */
class PhpGrid
{
    /**
     * @var string
     */
    protected $grid_name = "";

    /**
     * @var string
     */
    protected $title = "";

    /**
     * @var array
     */
    protected $params_list = [];

    /**
     * @var array
     */
    protected $column_list = [];

    /**
     * Query set by the user
     * @var string
     */
    protected $sql_query = null;

    /**
     * query generated by appliying filters and search
     * @var string
     */
    protected $generated_sql_query = null;
    /**
     * query generated for counting
     * @var string
     */
    protected string $generated_sql_count_query = "";

    protected string $generated_sql_totals_query = "";

    /**
     * Computed totals keyed by column name
     * @var array<string,float|int>|null
     */
    protected ?array $column_totals = [];

    /**
     * @var ActionButton[]
     */
    protected $actionButtons = [];

    /**
     * @var int
     */
    protected $rows_per_page = 10;

    /**
     * @var array
     */
    protected $filters = [];

    /**
     * @var array
     */
    protected $sortDetails = ['field' => null, 'dir' => 'ASC'];

    /**
     * @var int
     */
    protected $row_count = 0;
    /**
     * @var int
     */
    protected $page_count = 0;

    /**
     * results will be stored here
     * @var array
     */
    protected $data = [];

    /**
     * @var string
     */
    protected $errorMessage = "";

    /**
     * @var bool
     */
    protected $allowExport = true;

    /**
     * @var bool
     */
    protected $debug = false;

    /**
     * @var bool
     */
    protected $enableWildCardSearch = false;

    /**
     * @var bool
     */
    protected bool $showSearchBar = true;

    /**
     * @var bool
     */
    protected bool $showTitle = true;

    /**
     * Use PostgreSQL ILIKE for case-insensitive LIKE comparisons
     * Defaults to false to keep cross-DB parity using LOWER() technique
     * @var bool
     */
    protected bool $useIlikeOnPg = false;

    /**
     * Basic metrics for observability
     * @var float
     */
    protected float $execMs = 0.0;
    protected float $countMs = 0.0;


    /**
     * PhpGrid constructor.
     * @param string $gridName
     * @param array $params_list
     * @param array $filters
     * @throws \Exception
     */

    public function __construct(string $gridName, array $params_list = [], array $filters = [])
    {
        $this->setGridName($gridName);
        $this->setFilters($filters);
        if (!$this->hasFilters()) {
            $this->setFilters($_GET);
        }
        $this->setParamsList($params_list);
    }

    /**
     * Determine if a column should be treated as textual for case-insensitive operations
     */
    private function isTextualColumn(string $fieldName): bool
    {
        $col = $this->getColumn($fieldName);
        if (!$col) {
            return false;
        }
        $format = strtolower((string)$col->getFormat());
        // Common textual formats
        $textual = ['text', 'string', 'varchar', 'char', 'name', 'enum', 'uuid', 'citext'];
        return in_array($format, $textual, true) || $format === '' /* unknown -> be conservative: false */ && false;
    }

    /**
     * @return string
     */
    public function getGridName(): string
    {
        return $this->grid_name;
    }

    /**
     * @param string $grid_name
     * @return PhpGrid
     */
    public function setGridName(string $grid_name): PhpGrid
    {
        $this->grid_name = str_replace(' ', '_', $grid_name);
        return $this;
    }

    /**
     * @return array
     */
    public function getSortDetails(): array
    {
        return $this->sortDetails;
    }

    /**
     * @param string $field
     * @param string $direction
     * @return $this
     */
    public function setSortDetails(string $field, string $direction): PhpGrid
    {
        $this->sortDetails = ['field' => $field, 'dir' => $direction];
        return $this;
    }


    /**
     * @return null
     */
    public function getSqlQuery()
    {
        return $this->sql_query;
    }

    /**
     * @param null $sql_query
     * @return PhpGrid
     */
    public function setSqlQuery($sql_query)
    {
        $this->sql_query = $sql_query;
        return $this;
    }

    /**
     * @return string
     */
    public function getGeneratedSqlQuery(): string
    {
        return $this->generated_sql_query;
    }

    /**
     * @param string $generated_sql_query
     * @return PhpGrid
     */
    private function setGeneratedSqlQuery(string $generated_sql_query): PhpGrid
    {
        $this->generated_sql_query = $generated_sql_query;
        return $this;
    }

    /**
     * @return string
     */
    public function getGeneratedSqlCountQuery(): string
    {
        return $this->generated_sql_count_query;
    }

    public function getGeneratedSqlTotalsQuery(): string
    {
        return $this->generated_sql_totals_query;
    }

    public function setGeneratedSqlTotalsQuery(string $generated_sql_totals_query): PhpGrid
    {
        $this->generated_sql_totals_query = $generated_sql_totals_query;
        return $this;
    }



    /**
     * Define which columns should be totaled across all rows.
     * Accepts array of column names or comma-separated string.
     */
    public function setColumnTotals(array $columns = []): self
    {
        $this->column_totals = array_fill_keys($columns, 0);
        return $this;
    }

    /**
     * Get previously computed totals.
     */
    public function getColumnTotals(): ?array
    {
        return $this->column_totals;
    }

    /**
     * Compute totals for configured columns across ALL rows (ignoring pagination). Safe no-op if none configured.
     * This executes the data query to fetch all rows temporarily and restores the original page data afterwards.
     */
    protected function computeColumnTotalsIfNeeded(): void
    {
        if (count($this->column_totals) < 1) {
            return;
        }



        $db = Db::getInstance();
        try {
            $t0 = microtime(true);
            $stmt = $db->prepare($this->getGeneratedSqlTotalsQuery());
            foreach ($this->getParamsList() as $k => $v) {
                $stmt->bindValue(':' . $k, $v);
            }
            $stmt->execute();
            $res = $stmt->fetchAll(\PDO::FETCH_ASSOC);

            foreach($res as $k=>$v){
                if(array_key_exists($k, $this->column_totals)){
                    $this->column_totals[$k] = $v;
                }
            }
        }catch (\Throwable $ex){}

    }

    /**
     * @param string $generated_sql_count_query
     * @return PhpGrid
     */
    private function setGeneratedSqlCountQuery(string $generated_sql_count_query): PhpGrid
    {
        $this->generated_sql_count_query = $generated_sql_count_query;
        return $this;
    }


    /**
     * @return string
     */
    public function getTitle(): string
    {
        return $this->title;
    }

    /**
     * @param string $title
     * @return PhpGrid
     */
    public function setTitle(string $title): PhpGrid
    {
        $this->title = $title;
        return $this;
    }

    /**
     * @param array $filters
     * @return $this
     */
    public function setFilters(array $filters = []): PhpGrid
    {
        $this->filters = $filters;
        return $this;
    }

    /**
     * @return bool
     */
    public function getUseIlikeOnPg(): bool
    {
        return $this->useIlikeOnPg;
    }

    /**
     * @param bool $use
     * @return PhpGrid
     */
    public function setUseIlikeOnPg(bool $use): PhpGrid
    {
        $this->useIlikeOnPg = $use;
        return $this;
    }

    /**
     * @return array
     */
    public function getFilters(): array
    {
        return $this->filters;
    }

    /**
     * @return int
     */
    public function getFiltersCount(): int
    {
        return count($this->getFilters());
    }

    /**
     * @return bool
     */
    public function hasFilters(): bool
    {
        return $this->getFiltersCount() > 0;
    }

    /**
     * @param array $params_list
     * @return $this
     */
    public function setParamsList(array $params_list = []): PhpGrid
    {
        $this->params_list = $params_list;
        return $this;
    }

    /**
     * @return array
     */
    public function getParamsList(): array
    {
        return $this->params_list;
    }

    /**
     * @param string $key
     * @param string $value
     * @return $this
     */
    public function addParam(string $key, string $value): PhpGrid
    {
        $this->params_list[$key] = $value;
        return $this;
    }

    /**
     * @return ActionButton[]
     */
    public function getActionButtons(): array
    {
        return $this->actionButtons;
    }

    /**
     * @param ActionButton[] $actionButtons
     * @return PhpGrid
     */
    public function setActionButtons(array $actionButtons): PhpGrid
    {
        $this->actionButtons = $actionButtons;
        return $this;
    }

    /**
     * @param ActionButton $button
     * @return PhpGrid
     */
    public function addActionButton(ActionButton $button): PhpGrid
    {
        $this->actionButtons[] = $button;
        return $this;
    }


    /**
     * @param Column $column
     * @return $this
     */
    public function addColumn(Column $column): PhpGrid
    {
        $column->setIndex($this->getColumnsCount());
        $this->column_list[$column->getFieldName()] = $column;
        return $this;
    }

    /**
     * @return Column[]
     */
    public function getColumnsList(): array
    {
        return $this->column_list;
    }

    /**
     * @return int
     */
    public function getColumnsCount(): int
    {
        return count($this->column_list);
    }

    /**
     * @return string
     */
    public function getFirstColumnName(): string
    {
        $cols = array_keys($this->getColumnsList());
        return array_shift($cols);
    }

    /**
     * @param string $field_name
     * @return bool
     */
    public function hasColumn(string $field_name): bool
    {
        return array_key_exists($field_name, $this->column_list);
    }

    /**
     * @param string $fieldName
     * @return \Laf\UI\Grid\PhpGrid\Column|null
     */
    public function getColumn(string $fieldName): ?Column
    {
        if (array_key_exists($fieldName, $this->column_list)) {
            return $this->column_list[$fieldName];
        } else {
            return null;
        }
    }

    /**
     * @return int
     */
    public function getRowCount(): int
    {
        return $this->row_count;
    }

    /**
     * @param int $rowCount
     * @return PhpGrid
     */
    private function setRowCount(int $rowCount): PhpGrid
    {
        $this->row_count = $rowCount;
        $this->calculatePageCount();
        return $this;
    }

    /**
     * @return string
     */
    public function getErrorMessage(): string
    {
        return $this->errorMessage;
    }

    /**
     * @param string $errorMessage
     * @return PhpGrid
     */
    public function setErrorMessage(string $errorMessage): PhpGrid
    {
        $this->errorMessage = $errorMessage;
        return $this;
    }

    /**
     * @return int
     */
    public function getPageCount(): int
    {
        return $this->page_count;
    }

    /**
     * @param int $pageCount
     * @return PhpGrid
     */
    public function setPageCount(int $pageCount): PhpGrid
    {
        $this->page_count = $pageCount;
        return $this;
    }

    /**
     * @param bool $allowExport
     * @return $this
     */
    public function setAllowExport(bool $allowExport = true): PhpGrid
    {
        $this->allowExport = $allowExport;
        return $this;
    }

    /**
     * @return bool
     */
    public function getAllowExport(): bool
    {
        return $this->allowExport;
    }

    /**
     * @return int
     */
    public function getRowsPerPage(): int
    {
        return $this->rows_per_page;
    }

    /**
     * @param int $rowsPerPage
     * @return PhpGrid
     */
    public function setRowsPerPage(int $rowsPerPage): PhpGrid
    {
        $this->rows_per_page = $rowsPerPage;
        return $this;
    }

    /**
     * Looks at the amount of rows returned and
     * rows per page to display
     * then calculates the amount of pages it needs to list
     * and stores it in pageCount
     */
    private function calculatePageCount(): void
    {
        $rowsPerPage = $this->getRowsPerPage();
        if ($rowsPerPage == 0) {
            $this->setPageCount(1);
        } else {
            $rowCount = $this->getRowCount();
            if (!is_numeric($rowsPerPage) || $rowsPerPage == 0) {
                $rowsPerPage = 10;
            }

            $pages = (int)ceil($rowCount / $rowsPerPage);
            if ($pages < 1) {
                $pages = 1;
            }
            $this->setPageCount($pages);
        }
    }

    /**
     * Reads the columns field in the db record object
     * and sets up column settings in $columns property
     * @param BaseObject $dbObject
     * @throws \Exception
     */
    public function loadConfigFromObject(BaseObject $dbObject): void
    {
        $json = $dbObject->getColumnListVal();
        if (!Util::isJson($json)) {
            throw new \Exception("Invalid JSON config for Grid: " . $dbObject->getGridNameVal());
        }
        $jsonDecoded = json_decode($json, true);
        foreach ($jsonDecoded as $c) {
            $this->addColumn(Column::createFromAssocArray($c));
        }
        $this->setGridName($dbObject->getGridNameVal());
        $this->setActionButtons(json_decode($dbObject->getActionButtonsVal(), true));
        $this->setTitle($dbObject->getTitleVal());
        $this->setSqlQuery($dbObject->getSqlQueryVal());
        $this->setRowsPerPage($dbObject->getRowsPerPageVal());
        $this->setParamsList(Util::coalesce(json_decode($dbObject->getParamsListVal(), true), []));
    }


    /**
     * @return bool
     */
    public function getDebug(): bool
    {
        return $this->debug;
    }

    /**
     * @param bool $debug
     * @return PhpGrid
     */
    public function setDebug(bool $debug): PhpGrid
    {
        $this->debug = $debug;
        return $this;
    }


    /**
     * @param bool $getAllRows
     */
    protected function generateSql(bool $getAllRows = false): void
    {
        $filters = $this->filters;
        $page = 0;
        $isPg = $this->isPostgres();
        if ($this->getSortDetails()['field'] == '') {
            $this->setSortDetails($this->getFirstColumnName(), 'DESC');
        }

        if ($this->getRowsPerPage() == 0) {
            $this->setRowsPerPage(10);
        }
        $sqlWhere = '';


        if (isset($filters['page']) && is_numeric($filters['page'])) {
            $page = $filters['page'];
            $page--;
        }

        if (isset($filters['start']) && is_numeric($filters['start'])) {
            $start = $filters['start'];
        }

        if (isset($filters['limit']) && is_numeric($filters['limit']) && $filters['limit'] >= 0) {
            $limit = (int)$filters['limit'];
            // clamp limit to avoid huge scans (0 means all rows explicitly)
            if ($limit > 0) {
                $limit = max(1, min($limit, 1000));
            }
            $this->setRowsPerPage($limit);
        }

        // Security: Validate sort column against the list of known columns
        if (isset($filters['sort']) && $this->hasColumn(urldecode($filters['sort']))) {
            $this->sortDetails['field'] = urldecode($filters['sort']);
        }

        // Security: Whitelist sort direction
        if (isset($filters['dir']) && in_array(strtolower($filters['dir']), ['asc', 'desc'])) {
            $this->sortDetails['dir'] = $filters['dir'];
        }

        if (isset($filters['searchParams'])) {
            $sqlWhere .= " WHERE \n\t1=1 ";
            $searchParams = urldecode($filters['searchParams']);
            $searchParams = json_decode($searchParams);

            $searchParamsCount = 0;
            if(is_countable($searchParams)){
                $searchParamsCount = count($searchParams);
            }
            for ($i = 0; $i < $searchParamsCount; $i++) {
                $filterItem = $searchParams[$i];
                $requestedOperator = $filterItem->operator;
                $operator = $this->getOperator($requestedOperator);
                $value = $filterItem->value;
                $property = $filterItem->property;

                if (!$this->hasColumn($property))
                    // Security: if the column name is not valid, skip it.
                    continue;

                $phName = $this->sanitizePlaceholderName($property);
                // Per-column overrides
                $colCfg = $this->getColumn($property);
                if ($colCfg) {
                    if (!empty($colCfg->searchOperator)) {
                        $operator = $this->getOperator($colCfg->searchOperator);
                    }
                }

                // For PostgreSQL, decide case-insensitive strategy
                $propertyExpr = $property;
                $shouldLowercaseValue = false;
                if ($isPg) {
                    $useIlike = $this->getUseIlikeOnPg() && ($operator === 'LIKE');
                    if ($useIlike) {
                        $operator = 'ILIKE';
                    } else {
                        // Apply LOWER() only for textual comparisons or when column forces case-insensitive
                        $forceInsensitive = ($colCfg && ($colCfg->caseInsensitive === true || $colCfg->caseInsensitive === 1));
                        if (in_array($operator, ['LIKE', '=', '!='], true) || $forceInsensitive) {
                            $propertyExpr = "LOWER(" . $property . ")";
                            $shouldLowercaseValue = true;
                        }
                    }
                }

                $sqlWhere .= "\n\tAND " . $propertyExpr . " " . $operator . " :" . $phName;
                if ($operator == 'LIKE' || $operator == 'ILIKE') {
                    // Determine wildcard mode
                    $mode = 'contains';
                    if ($colCfg && !empty($colCfg->wildcardMode)) {
                        $mode = $colCfg->wildcardMode;
                    } else if ($this->isEnableWildCardSearch()) {
                        $mode = 'contains';
                    } else {
                        $mode = 'startswith';
                    }
                    if ($mode === 'startswith') {
                        $val = $value . '%';
                    } else if ($mode === 'endswith') {
                        $val = '%' . $value;
                    } else { // contains
                        $val = '%' . $value . '%';
                    }
                    if ($shouldLowercaseValue && is_string($val)) {
                        $val = function_exists('mb_strtolower') ? mb_strtolower($val) : strtolower($val);
                    }
                    $this->addParam($phName, $val);
                } else {
                    if ($shouldLowercaseValue && is_string($value)) {
                        $value = function_exists('mb_strtolower') ? mb_strtolower($value) : strtolower($value);
                    }
                    $this->addParam($phName, $value);
                }
            }
        }

        $start = $page * $this->getRowsPerPage();

        // Case-insensitive sort on PostgreSQL for textual columns or when column forces it
        $orderField = $this->sortDetails['field'];
        $orderExpr = $orderField;
        $forceInsensitiveSort = false;
        $colForSort = $this->getColumn($orderField);
        if ($colForSort && ($colForSort->caseInsensitiveSort === true || $colForSort->caseInsensitiveSort === 1)) {
            $forceInsensitiveSort = true;
        }
        if ($isPg && ($this->isTextualColumn($orderField) || $forceInsensitiveSort)) {
            $orderExpr = "LOWER(" . $orderField . ")";
        }
        $sqlOrderBy = " ORDER BY {$orderExpr} {$this->sortDetails['dir']} \n";

        $sqlLimit = "";
        if ($this->getRowsPerPage() > 0 && !$getAllRows) {
            $sqlLimit .= " LIMIT {$this->getRowsPerPage()} OFFSET {$start} \n";
        }

        $this->setGeneratedSqlQuery("
            -- grid query: {$this->getGridName()}  
            SELECT 
            " . join(',', array_keys($this->getColumnsList())) . " 
            FROM (
                {$this->getSqlQuery()}
            ) {$this->getGridName()} 
            {$sqlWhere}
            {$sqlOrderBy}
            {$sqlLimit}
            "
        );

        $this->setGeneratedSqlCountQuery("
            -- grid counter: {$this->getGridName()}  
            SELECT 
                COUNT(*) as total_number_of_rows 
            FROM (
                SELECT 
                " . $this->getFirstColumnName() . " 
                FROM (
                    {$this->getSqlQuery()}
                ) {$this->getGridName()} 
                {$sqlWhere}
            ) {$this->getGridName()}_count
        "
        );

        $totalscolumns = [];
        foreach($this->getColumnTotals() as $key=>$value){
            $totalscolumns[] = " SUM(".$key.") AS ".$key." ";
        }

        $this->setGeneratedSqlTotalsQuery("
            -- grid totals: {$this->getGridName()}  
            SELECT 
                ".join(',', $totalscolumns)."
            FROM (
                SELECT 
                " . $this->getFirstColumnName() . " 
                FROM (
                    {$this->getSqlQuery()}
                ) {$this->getGridName()} 
                {$sqlWhere}
            ) {$this->getGridName()}_count
        "
        );

    }

    /**
     * @return bool
     */
    private function isPostgres(): bool
    {
        try {
            $db = Db::getInstance();
            $driver = strtolower((string)$db->getAttribute(\PDO::ATTR_DRIVER_NAME));
            return $driver === 'pgsql' || $driver === 'postgres' || $driver === 'postgresql';
        } catch (\Throwable $e) {
            return false;
        }
    }

    /**
     * @param $operator
     * @return string
     */
    protected function getOperator($operator): string
    {
        switch ($operator) {
            case 'lt':
                return '<';
                break;
            case 'gt':
                return '>';
                break;
            case 'lteq':
                return '<=';
                break;
            case 'gteq':
                return '>=';
                break;
            case 'eq':
            case 'stricteq':
                return '=';
                break;
                break;
            case 'noteq':
            case 'notstricteq':
                return '!=';
                break;
            case 'like':
            default:
                return 'LIKE';
                break;
        }
    }

    /**
     * @return bool
     */
    protected function isValid(): bool
    {
        if (strlen($this->getSqlQuery()) < 10) {
            $this->errorMessage = "Missing SQL Query";
            return false;
        }
        if ($this->getColumnsCount() < 2) {
            $this->errorMessage = "Missing column information";
            return false;
        }
        if ($this->getGridName() == '') {
            $this->errorMessage = "Missing grid name";
            return false;
        }
        return true;
    }

    /**
     * Runs the query and generates JSON data
     * Store JSON data in _json_value
     * and return it
     * @param bool $getAllRows
     * @return bool
     * @throws \Throwable
     */
    public function execute(bool $getAllRows = false): bool
    {
        $data = [];

        if (!$this->isValid()) {
            return false;
        }

        $this->generateSql($getAllRows);

        $db = Db::getInstance();
        try {
            $t0 = microtime(true);
            $stmt = $db->prepare($this->getGeneratedSqlQuery());
            foreach ($this->getParamsList() as $k => $v) {
                $stmt->bindValue(':' . $k, $v);
            }
            $stmt->execute();
            $this->data = $stmt->fetchAll(\PDO::FETCH_ASSOC);
            $this->execMs = (microtime(true) - $t0) * 1000.0;

            for ($i = 0; $i < $stmt->columnCount(); $i++) {
                $tmp = $stmt->getColumnMeta($i);
                $col = $this->getColumn($tmp['name']);
                if ($col) {
                    $native = $tmp['native_type'] ?? '';
                    $col->setFormat($this->convertNativeDataTypeToString((string)$native));
                }
                $this->setRowCount(count($this->data));
            }

            if (!is_array($this->data)) {
                return false;
            }

            if (!$getAllRows) {
                $tc0 = microtime(true);
                $stmtCount = $db->prepare($this->getGeneratedSqlCountQuery());
                foreach ($this->getParamsList() as $k => $v) {
                    $stmtCount->bindValue(':' . $k, $v);
                }
                $stmtCount->execute();
                $this->setRowCount(($stmtCount->fetchObject())->total_number_of_rows);
                $this->countMs = (microtime(true) - $tc0) * 1000.0;
            }

            $this->computeColumnTotalsIfNeeded();


        } catch (\Throwable $ex) {
            $this->errorMessage = 'An error has occurred while generating grid data. ';
            if($this->getDebug()){
                $this->errorMessage .= json_encode($ex->getMessage(). ' - '. $ex->getTraceAsString());
            }
        }
        return true;
    }

    /**
     * @throws \Exception
     */
    public function bootstrap()
    {
        if (array_key_exists('export_grid_to_excel', $this->filters) && $this->filters['export_grid_to_excel'] == 1) {
            $this->exportToExcelPhpExcel();
        } else if (array_key_exists('export_grid_to_excel', $this->filters) && $this->filters['export_grid_to_excel'] == 2) {
            $this->exportToExcelSpout();
        } else if (array_key_exists('export_grid_to_csv', $this->filters)) {
            $this->exportToCsv();
        } else {
            $this->outputJsonWithHeaders();
        }
    }

    /**
     * Export data to Excel using Spreadsheet
     * @return null
     * @throws \Throwable
     */
    public function exportToExcelPhpExcel()
    {
        if (!$this->getAllowExport()) {
            return null;
        }
        ob_clean();
        $_column = 'A';
        $_row = 1;
        $workbook = new Spreadsheet();
        $fileName = $this->getGridName() . ' ('.date('Y-m-d Hi').').xlsx';

        $sheet = $workbook->getActiveSheet();

        /**
         * set heading row
         */
        $headingRow = [];
        foreach ($this->getColumnsList() as $column) {
            $headingRow[] = $column->getLabel();
        }
        $sheet->fromArray($headingRow, '', $_column . $_row);
        $sheet->getStyle('A1:' . $this->columnNumberToLetter($this->getColumnsCount()) . '1')->applyFromArray([
            'font' => [
                'bold' => true,
                'color' => ['rgb' => 'ffffff']
            ],
            'alignment' => ['horizontal' => 'center'],
            'fill' => [
                'fillType' => 'solid',
                'color' => ['rgb' => '000000']
            ]

        ]);
        $_row++;


        $this->execute(true);
        foreach ($this->data as $row) {
            $sheet->fromArray($row, '', $_column . $_row);
            $_row++;
        }

        /**
         * Set auto width
         */
        Font::setAutoSizeMethod(Font::AUTOSIZE_METHOD_APPROX);
        $cellIterator = $sheet->getRowIterator()->current()->getCellIterator();
        $cellIterator->setIterateOnlyExistingCells(true);
        foreach ($cellIterator as $cell) {
            $sheet->getColumnDimension($cell->getColumn())->setAutoSize(true);
        }

        $sheet->setSelectedCell('A1');
        $writer = new Xlsx($workbook);

        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="' . $fileName . '"');
        header('Cache-Control: max-age=0');
        $writer->save('php://output');

        //log exec time
        //log peak memory
        exit;
    }

    /**
     * Export data to Excel via Spout
     * @throws IOException
     * @throws WriterNotOpenedException
     */
    public function exportToExcelSpout()
    {
        $fileName = $this->getGridName() . ' ('.date('Y-m-d Hi').').xlsx';

        if (ob_get_level() > 0) { @ob_clean(); }
        if (!headers_sent()) {
            header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
            header('Content-Disposition: attachment;filename="' . $fileName . '"');
            header('Cache-Control: max-age=0');
        }

        if (!$this->getAllowExport()) {
            return null;
        }

        $w = WriterEntityFactory::createXLSXWriter();
        $w->openToBrowser($fileName);

        $headingRow = [];
        foreach ($this->getColumnsList() as $column) {
            $headingRow[] = $column->getLabel();
        }
        $headingRowStyle = ((new StyleBuilder())
            ->setFontBold()
            ->setFontColor(Color::WHITE)
            ->setBackgroundColor(Color::BLACK))->build();

        $border = ((new BorderBuilder())
            ->setBorderTop(Color::BLACK, Border::WIDTH_THIN)
            ->setBorderRight(Color::BLACK, Border::WIDTH_THIN)
            ->setBorderBottom(Color::BLACK, Border::WIDTH_THIN)
            ->setBorderLeft(Color::BLACK, Border::WIDTH_THIN)
        )->build();

        $defaultStyle = ((new StyleBuilder())
            ->setBorder($border)
        )->build();
        $w->setDefaultRowStyle($defaultStyle);


        $row = WriterEntityFactory::createRowFromArray($headingRow, $headingRowStyle);
        $w->addRow($row);

        $this->execute(true);
        foreach ($this->data as $row) {
            $row = WriterEntityFactory::createRowFromArray($row);
            $w->addRow($row);
        }

        $w->close();
        exit;
    }

    public function exportToCsv()
    {
        if (!$this->getAllowExport()) {
            return null;
        }

        $fileName = $this->getGridName() . ' ('.date('Y-m-d Hi').').csv';

        if (ob_get_level() > 0) { @ob_clean(); }
        if (!headers_sent()) {
            header('Content-Type: text/csv');
            header('Content-Disposition: attachment;filename="' . $fileName . '"');
            header('Cache-Control: max-age=0');
        }

        $headingRow = [];
        foreach ($this->getColumnsList() as $column) {
            $headingRow[] = $column->getLabel();
        }

        $this->execute(true);
        $file = fopen('php://output', 'wb');
        fputcsv($file, $headingRow);
        foreach ($this->data as $row) {
            fputcsv($file, $row);
        }
        fclose($file);
        exit;
    }

    /**
     * Output Json clearing the buffer and setting proper json headers
     * If the results are not generated, it would re-run it
     * @param bool $reload_results
     * @return void
     * @throws \Exception
     */
    #[NoReturn]
    public function outputJsonWithHeaders(bool $reload_results = false): void
    {
        if (ob_get_level() > 0) { @ob_clean(); }
        if (!headers_sent()) {
            header('Content-Type: application/json');
        }

        // Re-execute only when needed
        $executed = true;
        if (count($this->data) < 1 || $reload_results) {
            $executed = $this->execute();
        }

        $success = ($this->getErrorMessage() === "") && $executed;
        $errorCode = null;

        // Decide and set HTTP status code on failure
        if (!$success && !headers_sent()) {
            $msg = $this->getErrorMessage();
            $validationErrors = [
                "Missing SQL Query",
                "Missing column information",
                "Missing grid name",
            ];
            if (in_array($msg, $validationErrors, true)) {
                http_response_code(400);
                $errorCode = 'ERR_VALIDATION';
            } else {
                http_response_code(500);
                $errorCode = 'ERR_RUNTIME';
            }
        }

        // Compute totals across all rows if requested
        try {
            $this->computeColumnTotalsIfNeeded();
        } catch (\Throwable $e) {
            // Keep grid responsive even if totals fail
            $this->column_totals = null;
        }

        $data = [
            'success' => $success,
            'id' => 1,
            'name' => $this->getGridName(),
            'title' => $this->getTitle(),
            'columns' => $this->getColumnsList(),
            'columnCount' => $this->getColumnsCount(),
            'actionButtons' => $this->getActionButtons(),
            'message' => $this->getErrorMessage(),
            'sort' => $this->getSortDetails()['field'],
            'dir' => $this->getSortDetails()['dir'],
            'errorCode' => $errorCode,
            'pageCount' => $this->getPageCount(),
            'rowsPerPage' => $this->getRowsPerPage(),
            'allowExport' => $this->getAllowExport(),
            'rowCount' => $this->getRowCount(),
            // Debug fields (keep backward compatibility and align with JS expectations)
            'user_query' => ($this->getDebug() ? $this->getSqlQuery() : null),
            'generated_query' => ($this->getDebug() ? $this->getGeneratedSqlQuery() : null),
            'generated_counter_query' => ($this->getDebug() ? $this->getGeneratedSqlCountQuery() : null),
            'query' => ($this->getDebug() ? $this->getSqlQuery() : null),
            'queryCount' => ($this->getDebug() ? $this->getGeneratedSqlCountQuery() : null),
            'metrics' => ($this->getDebug() ? ['execMs' => round($this->execMs,2), 'countMs' => round($this->countMs,2)] : null),
            'columnTotals' => $this->getColumnTotals(),
            'rows' => $this->data
        ];
        echo json_encode($data);

        if (ob_get_level() > 0) { @ob_end_flush(); }
        exit;
    }

    /**
     * @return string
     */
    #[Pure] public function draw(): string
    {
        $gridName = $this->getGridName();
        $header = "";
        foreach ($this->getColumnsList() as $column) {
            $header .= "<th>" . $column->getLabel() . '</th>';
        }

        $html =
            "
<script type='text/javascript'>
\twindow.grid = window.grid || {};
\twindow.grid['{$gridName}'] = new Grid('{$gridName}');
\twindow.grid['{$gridName}']._rowsPerPage = {$this->getRowsPerPage()};
\twindow.grid['{$gridName}'].showTitleBar = ".(var_export($this->getShowTitle(), true)).";
\twindow.grid['{$gridName}'].showSearchBar = ".(var_export($this->getShowSearchBar(), true)).";
\t\$(document).ready(function () {
\t     window.grid['{$gridName}'].initialize();
\t});
</script>
<div id='{$gridName}_container' data-rows-per-page='{$this->getRowsPerPage()}' data-show-title-bar='".(var_export($this->getShowTitle(), true))."' data-show-search-bar='".(var_export($this->getShowSearchBar(), true))."'>
  <div class='table-responsive' style='position:relative;overflow: visible'>
\t<table id='{$gridName}' data-component-type='Grid' class='table table-striped table-bordered table-hover table-sm table-responsive-md'  style='margin-bottom:0;'>
\t\t<thead id='{$gridName}_thead' class='thead-light'>
\t\t\t<tr id='{$gridName}_title_row'>
\t\t\t\t<th style='text-align: left'  id='{$gridName}_title'></th>
\t\t\t\t<th style='text-align: right' id='{$gridName}_buttons'></th>
\t\t\t</tr>
\t\t\t<tr></tr>
\t\t\t<tr class='d-print-none'></tr>
\t\t</thead>
\t\t<tbody id='{$gridName}_tbody'>
\t\t</tbody>
\t\t<tfoot>
\t\t</tfoot>
\t</table>
\t
\t<div>
\t\t<div class='d-flex justify-content-between'>
\t\t\t<div id='{$gridName}_paginationInfoSection' class='m-0 py-2 small'></div>
\t\t\t<div class='row m-0 py-2'>
\t\t\t\t<div class='col'>
\t\t\t\t\t<span class='dropdown'>
\t\t\t\t\t\t<button title='Choose how many rows to show per page' class='btn btn-outline-secondary btn-sm dropdown-toggle' type='button' id='{$gridName}_rowsPerPageSelector' data-toggle='dropdown' data-bs-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>10</button>
\t\t\t\t\t\t<span class='dropdown-menu text-right' aria-labelledby='{$gridName}_pagesPerRowSelector'>
\t\t\t\t\t\t\t<a class='dropdown-item' href='javascript:;' onclick=\"window.grid['{$gridName}'].setRowsPerPage(10);\">10</a>
\t\t\t\t\t\t\t<a class='dropdown-item' href='javascript:;' onclick=\"window.grid['{$gridName}'].setRowsPerPage(50);\">50</a>
\t\t\t\t\t\t\t<a class='dropdown-item' href='javascript:;' onclick=\"window.grid['{$gridName}'].setRowsPerPage(100);\">100</a>
\t\t\t\t\t</span>
\t\t\t\t</span>
\t\t\t</div>
\t\t\t<div class='col'>
\t\t\t\t<nav aria-label='Navigation'>
\t\t\t\t\t<ul class='Laf-SimpleTable-Pagination pagination pagination-sm'>
\t\t\t\t\t\t<li class='page-item'><a id='{$gridName}_paginationFirstPage' href='javascript:;' class='page-link' title='First Page'><i class='fa fa-angle-double-left'></i></a></li>
\t\t\t\t\t\t<li class='page-item'><a id='{$gridName}_paginationPrevPage' href='javascript:;' class='page-link' title='Previous Page'><i class='fa fa-angle-left'></i></a></li>
\t\t\t\t\t\t<li class='page-item'><a id='{$gridName}_paginationCurrPage' href='javascript:;' class='page-link' title='Current Page'>1</a></li>
\t\t\t\t\t\t<li class='page-item '><a  id='{$gridName}_paginationNextPage' href='javascript:;' class='page-link' title='Next Page'><i class='fa fa-angle-right'></i></a></li>
\t\t\t\t\t\t<li class='page-item'><a id='{$gridName}_paginationLastPage' href='javascript:;' class='page-link' title='Last Page'><i class='fa fa-angle-double-right'></i></a></i>
\t\t\t\t\t</ul>
\t\t\t\t</nav>
\t\t\t</div>
\t\t</div>
\t</div>
\t<div id='{$gridName}_loader' style='background-color: lightgray; z-index:85; position:absolute; top:0px; left:0px; width:100%; height:100%; opacity:.5; text-align: center;padding:20px; display:none;'>
\t\t<div class='fa-5x'><i class='fas fa-spinner fa-spin' style='color:#000000;'></i></div>
\t</div>
</div>
</div>
";
        return $html;
    }

    /**
     * To match excel format 1-A 2-B
     * Example: input = 1; output = A
     * @param $c
     * @return string
     */
    #[Pure] public function columnNumberToLetter($c)
    {
        $c = intval($c);
        if ($c <= 0) return '';

        $letter = '';

        while ($c != 0) {
            $p = ($c - 1) % 26;
            $c = intval(($c - $p) / 26);
            $letter = chr(65 + $p) . $letter;
        }

        return $letter;
    }

    /**
     * Convert native mysql datatype to string
     * @param string $type
     * @return string
     */
    private function convertNativeDataTypeToString(string $type): string
    {
        $t = strtoupper($type);
        switch ($t) {
            case 'FLOAT':
            case 'DOUBLE':
            case 'NEWDECIMAL':
            case 'DECIMAL':
            case 'NUMERIC':
                return 'float';
            case 'INT':
            case 'INTEGER':
            case 'LONG':
            case 'TINY':
            case 'SHORT':
            case 'BIGINT':
            case 'SMALLINT':
                return 'integer';
            case 'DATE':
                return 'date';
            case 'TIME':
                return 'time';
            case 'DATETIME':
            case 'TIMESTAMP':
                return 'datetime';
            case 'VAR_STRING':
            default:
                return 'string';
        }
    }

    /**
     * Sanitize a string to be used as a PDO placeholder name
     * @param string $name
     * @return string
     */
    private function sanitizePlaceholderName(string $name): string
    {
        return preg_replace('/[^A-Za-z0-9_]/', '_', $name);
    }

    /**
     * Checks if the request has necessary params to handle json requests
     * @return bool
     */
    #[Pure]
    public function isReadyToHandleRequests()
    {
        return array_key_exists('load_grid_by_name', $this->getFilters()) && $this->getFilters()['load_grid_by_name'] == $this->getGridName();
    }

    /**
     * @return bool
     */
    public function isEnableWildCardSearch(): bool
    {
        return $this->enableWildCardSearch;
    }

    /**
     * @param bool $enableWildCardSearch
     * @return PhpGrid
     */
    public function setEnableWildCardSearch(bool $enableWildCardSearch): PhpGrid
    {
        $this->enableWildCardSearch = $enableWildCardSearch;
        return $this;
    }

    /**
     * @return bool
     */
    public function getShowSearchBar(): bool
    {
        return $this->showSearchBar;
    }

    /**
     * @param bool $showSearchBar
     * @return PhpGrid
     */
    public function setShowSearchBar(bool $showSearchBar): PhpGrid
    {
        $this->showSearchBar = $showSearchBar;
        return $this;
    }

    /**
     * @return bool
     */
    public function getShowTitle(): bool
    {
        return $this->showTitle;
    }

    /**
     * @param bool $showTitle
     * @return PhpGrid
     */
    public function setShowTitle(bool $showTitle): PhpGrid
    {
        $this->showTitle = $showTitle;
        return $this;
    }

}
