<?php

namespace Laf\UI\Form\Input;

use Laf\UI\ComponentInterface;
use Laf\UI\Form\FormElementInterface;
use Laf\UI\Form\InputType;

class Checkbox extends Text implements FormElementInterface, ComponentInterface
{
    public function drawUpdateMode()
    {
        $this->setType(InputType::Checkbox);
        if ($this->getValue()) {
            $this->getField()->getFormElement()->setAttribute('checked', 'checked');
        }
        return parent::drawUpdateMode();
    }

    public function drawViewMode()
    {
        $newVal = null;
        if($this->getValue() == 1){
            $newVal = 'Yes';
        }else if($this->getValue() == 0{
            $newVal = 'No';
        }else{
            $newVal = '&nbsp;';
        }
        $this->setValue($newVal);
        return parent::drawViewMode(); // TODO: Change the autogenerated stub
    }

    /**
     * Returns the CSS class unique to the UI component
     * @return string
     */
    public function getComponentCssControlClass(): string
    {
        return str_replace('\\', '-', static::class);
    }
}
